### ISSUE TITLE
Finalize invertible commands for FinanceTracker, CcaTracker, Planner, CoursePlanner

### ISSUE THREAD

**Issue by marcfyk** [AY1920S1-CS2103T-T10-1/main#183]
Finalize invertible commands so that they can be adapted to `JSON`.

- ensure class members and logic are correct
- complete testing for execution and inverse execution

**Please comment on this issue your commands that are invertible.**
Thanks :D

- [x] @mrnewguy 
- [x] @ryanYtan 
- [x] @nishcafe 
- [x] @gohsnn

**Comment by ryanYtan** [comment]
`AddCourseCommand` and `DeleteCourseCommand`

**Comment by gohsnn** [comment]
`SetPaidCommand`, `SetInstallmentCommand`, `RemovePaidCommand`, `RemoveInstallmentCommand`, `EditInstallmentCommand`

**Comment by nishcafe** [comment]
`AddTaskCommand`, `DeleteTaskCommand`, `DoneTaskCommand`

**Comment by mrnewguy** [comment]
AddCcaCommand, AddProgressCommand, DeleteCcaCommand, EditCcaCommand, IncreaseProgressCommand

**Comment by marcfyk** [comment]
Thanks
