### ISSUE TITLE
Study Planner Feature

### ISSUE THREAD

**Issue by nishcafe** [AY1920S1-CS2103T-T10-1/main#27]
# Overview
The planner enables users to manage tasks in JARVIS. The three task types are `todo`, `deadline` and `event`. Users are able to sort tasks by tags, priority levels or frequency.

# Command Format
* `add t/TASK TYPE des/TASK DES [d/DATE] [#TAG]... [p/PRIORITY LEVEL] [f/FREQ]`
* `delete INDEX` or `delete t/TASK DES`
* `clear [#TAG]... [d/DATE]`
* `find KEYWORD...`
* `list d/DATE` or `list #TAG…`
* `edit t/TASK DES/NEW DES` or `edit INDEX/NEW DES`
* `create #TAG...`
* `sort #TAG...`
* `done INDEX`
* `stats`

**Comment by ryanYtan** [comment]
Fixed in #397
