### ISSUE TITLE
Update all command responses to reflect accurate command syntax

### ISSUE THREAD

**Issue by gohsnn** [AY1920S1-CS2103T-T10-1/main#316]

**Comment by gohsnn** [comment]
This has been done for Finance Tracker feature, for the commands:

- `SetPaidCommand`

- `SetInstallmentCommand`

- `RemovePaidCommand`

- `RemoveInstallmentCommand`

- `SetMonthlyLimitCommand`

- `ListFinancesCommand`

**Comment by ryanYtan** [comment]
Fixed in v1.4
